version: "3.8"

services:
  html2pdf:
    container_name: html2pdf
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    restart: always
