[service]
name = "html2pdf-service"

[[deployments]]
name = "html2pdf"
path = "."
dockerfile = "Dockerfile"
start_cmd = "npm run start"
# Comando para iniciar el servicio html2pdf. Si es otro comando, cámbialo aquí.

[[deployments]]
name = "minio"
image = "minio/minio"
start_cmd = "minio server --console-address :9001 /data"
# Railway gestionará automáticamente la imagen de MinIO.

[envs]
# Configuración de MinIO
MINIO_ENDPOINT = "minio"
MINIO_PORT = "9000"
MINIO_ROOT_USER = "your_minio_user"   # Añade aquí el valor correspondiente
MINIO_ROOT_PASSWORD = "your_minio_password"   # Añade aquí el valor correspondiente
MINIO_USE_SSL = "false"
MINIO_BUCKET = "pdfs"

# Configuración de Railway
PUBLIC_DOMAIN = "mi-app.railway.app"

# Configuración del servidor
PORT = "3000"  # Puerto en el que corre tu aplicación Express

[[plugins]]
name = "volumes"
type = "volume"
path = "/data"
volume_name = "minio_data"
